
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: archingvar/docker-project-74:latest
    container_name: app
#    volumes:
#      - ./app:/app
    working_dir: /app
    command: ["make", "test"]
