
version: '3.8'

services:
  app:
    depends_on: 
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile.production
    image: archingvar/docker-project-74:latest
    container_name: app
#    volumes:
#      - ./app:/app
    working_dir: /app
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password

    command: ["make", "test"]
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  
