version: '3.8'

services:
  app:
    build: .
    container_name: app
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "8080:8080"  # Example port mapping (adjust if needed)
    command: ["make", "dev"]  # Adjust this to match your app's entry file
